"""empty message

Revision ID: 304d3a3493e4
Revises: 0d675eaede28
Create Date: 2020-11-24 21:31:18.313073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304d3a3493e4'
down_revision = '0d675eaede28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'past_shows_count')
    # ### end Alembic commands ###
